apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-monitor
    spec:
      containers:
        - name: deployment-studio-container
          image: "icr.io/test/monitor-test"
          ports:
            - containerPort: 8080          
          imagePullPolicy: IfNotPresent          
      restartPolicy: Always